version: "3.6"

services:
  developer-docs:
      image: "dojima-docs"
      ports:
      - "0.0.0.0:83:83"
      container_name: "serve-dojima-docs"
      working_dir: /workspace/
      volumes:
        - type: bind
          source: .
          target: /workspace
